packages:
- '.'
- location:
    git: https://github.com/sbidin/sdl2-mixer
    commit: bbb6eb10896d228c384decee7e6b61558c78e3ad
  extra-dep: true
- location:
    git: https://github.com/sbidin/sdl2-image
    commit: 5ea4a9f8d1ccb7227d54669a143e5ae3c554040a
  extra-dep: true

resolver: lts-7.3

rebuild-ghc-options: true
ghc-options:
    flappy-haskell: "-threaded -O2 -rtsopts -with-rtsopts=-N -Wall -lSDL2_image -lSDL2_mixer"
