packages:
- '.'
- sdl2-image
- sdl2-mixer
extra-deps:
- sdl2-2.1.0
- Yampa-0.10.3
resolver: lts-3.13
rebuild-ghc-options: true
ghc-options:
    flappy-haskell: "-threaded -O2 -rtsopts -with-rtsopts=-N -Wall -lsdl2_image -lsdl2_mixer"
